### ISSUE TITLE
ERROR: Unrecognized pair style 'lj/cut/ppa' (../force.cpp:278)

### ISSUE THREAD

**Issue by olajuwonOT** [t-murash/LAMMPS-PPA#1]
Hi,

I am currently a doctoral student from University of Florida, trying to use the PPA package for my work. 
I installed and build lammps with cmake by following the readme file. However, I ran into an issue "ERROR: Unrecognized pair style 'lj/cut/ppa' (../force.cpp:278)" after running the lammps using the example file provided. I see that the pair style is not recognized. I would appreciate your insights to this issue. Thank you

**Comment by t-murash** [comment]
Thank you for your bug report.
I have now checked in the latest LAMMPS version, "2Aug2023". 
PPA works fine.

Perhaps, your installation process has some problem.

Type "cmake ../cmake" at your "build" directory.
"Enabled packages" can be found in the log message as shown below.

"--  Enabled packages: MOLECULE, PPA"

If you cannot find "PPA", your cmake was failed.
In this case, you skipped to edit some setting files for cmake or forgot "-DPKG_PPA=yes".
Please read the "README.md" page again, and correctly build LAMMPS with PPA.

**Comment by olajuwonOT** [comment]
Hi,
I re - installed the package using the cmake approach. The pairstyle still cannot be recognized. 
I typed "cmake ../cmake" in using the terminal in the build directory. Attached is a snapshot of the log message. Thank you for your time.
Regards,Taofeek Tejuosho
    On Tuesday, 5 September 2023 at 18:45:30 GMT-4, T. Murashima ***@***.***> wrote:  
 
 


Thank you for your bug report.
I have now checked in the latest LAMMPS version, "2Aug2023".
PPA works fine.

Perhaps, your installation process has some problem.

Type "cmake ../cmake" at your "build" directory.
"Enabled packages" can be found in the log message as shown below.

"-- Enabled packages: MOLECULE, PPA"

If you cannot find "PPA", your cmake was failed.
In this case, you skipped to edit some setting files for cmake or forgot "-DPKG_PPA=yes".
Please read the "README.md" page again, and correctly build LAMMPS with PPA.

**Comment by t-murash** [comment]
I cannot find your attached file because you replied by e-mail.
But anyway, I understand that your installing process still has some problem.
Perhaps, no error messages are shown during building process.
In that case, you built LAMMPS without the "PPA" source files.

Please type "./lmp -help | grep ppa". 
If your LAMMPS binary was successfully built with PPA, "lj/cut/ppa" and "fene/ppa" will be shown in your terminal as below.

![screenshot](https://github.com/t-murash/LAMMPS-PPA/assets/36721596/1c5d27d0-5b8f-4689-94a9-269188c00cbb)

Perhaps, your terminal shows nothing.

Please check your "src" directory of LAMMPS.
Can you find "PPA" directory? 
--> If no, copy "LAMMPS-PPA/PPA" as "cp LAMMPS-PPA/PPA lammps-2Aug/2023/src/."

If you find PPA directory in "src" directory, are there 6 source files?
-->If no, copy source files in "LAMMPS-PPA/PPA" to LAMMPS "src" directory as "cp LAMMPS-PPA/PPA/* lammps-2Aug/2023/src/PPA/."

Then, rebuild it.

**Comment by t-murash** [comment]
If you need further assistance, please e-mail me. I will close this issue.
